# Generated by Django 3.1.7 on 2021-04-13 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20210412_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspermissions',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_permissions', to='business.businessposition'),
        ),
    ]
