# Generated by Django 3.1.7 on 2021-04-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_log'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='businessposition',
            constraint=models.UniqueConstraint(fields=('business', 'position'), name='unique position'),
        ),
    ]
