# Generated by Django 3.1.7 on 2021-05-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_business_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='zip_code',
            field=models.PositiveIntegerField(default='233', null=True),
        ),
    ]
