# Generated by Django 3.1.7 on 2021-05-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20210508_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institution/logo'),
        ),
    ]
