# Generated by Django 3.1.7 on 2021-05-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_auto_20210517_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='country_code',
            field=models.PositiveIntegerField(default='233'),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business/logo'),
        ),
    ]
