# Generated by Django 3.2.3 on 2021-06-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='country_code',
            field=models.CharField(blank=True, default='233', max_length=30),
        ),
    ]
