# Generated by Django 3.2.3 on 2021-06-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_auto_20210613_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspermissions',
            name='allowed',
            field=models.CharField(choices=[('Manage Inventory', 'MANAGE INVENTORY'), ('Make Sales', 'MAKE SALES'), ('Manage Sales', 'MANAGE SALES'), ('Access Accounts', 'ACCESS ACCOUNTS'), ('Manage Accounts', 'MANAGE ACCOUNTS'), ('Manage Employees', 'MANAGE EMPLOYEES')], max_length=30),
        ),
    ]
