# Generated by Django 3.2.3 on 2021-06-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_alter_businesspermissions_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspermissions',
            name='allowed',
            field=models.CharField(choices=[('manage inventory', 'MANAGE INVENTORY'), ('make sales', 'MAKE SALES'), ('manage sales', 'MANAGE SALES'), ('access accounts', 'ACCESS ACCOUNTS'), ('manage accounts', 'MANAGE ACCOUNTS'), ('manage employees', 'MANAGE EMPLOYEES')], max_length=30),
        ),
    ]
