# Generated by Django 3.1.7 on 2021-04-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20210415_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoicelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
