# Generated by Django 3.1.7 on 2021-04-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoicelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoicelog',
        ),
    ]
