# Generated by Django 3.1.7 on 2021-04-16 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20210416_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='serviced_item',
        ),
        migrations.AlterField(
            model_name='serviceditem',
            name='invoice_item',
            field=models.ForeignKey(limit_choices_to={'inventory.serviced_item': 'True'}, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoiceitem'),
        ),
    ]
