# Generated by Django 3.1.7 on 2021-04-16 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_log'),
        ('invoice', '0007_auto_20210416_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceditem',
            name='employee_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='serviceditem',
            name='serviced_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.employee'),
        ),
        migrations.AlterField(
            model_name='serviceditem',
            name='invoice_item',
            field=models.OneToOneField(limit_choices_to={'inventory__serviced_item': 'True'}, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoiceitem'),
        ),
    ]
