# Generated by Django 3.1.7 on 2021-04-16 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_log'),
        ('invoice', '0009_auto_20210416_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('employee_name', models.CharField(blank=True, max_length=30)),
                ('invoice_item', models.OneToOneField(limit_choices_to={'inventory__serviced_item': 'True'}, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoiceitem')),
                ('rejected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.employee')),
            ],
        ),
    ]
