# Generated by Django 3.1.7 on 2021-05-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_rejecteditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_contact',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
