# Generated by Django 3.1.7 on 2021-05-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_auto_20210511_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
