# Generated by Django 3.2.3 on 2021-06-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_auto_20210517_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
