# Generated by Django 3.2.3 on 2021-06-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_invoiceitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='serviced_item_finished',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='serviced_item_image_check',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
