# Generated by Django 3.2.3 on 2021-06-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_auto_20210617_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
