# Generated by Django 3.1.7 on 2021-04-14 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0006_auto_20210413_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('product', 'PRODUCT'), ('service', 'SERVICE')], max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('unit', models.CharField(max_length=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='business.business')),
            ],
            options={
                'ordering': ['business'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique inventory name'),
        ),
    ]
