# Generated by Django 3.1.7 on 2021-04-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210414_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.CharField(choices=[('hour', 'hour'), ('min', 'minute'), ('day', 'day'), ('other', 'other')], max_length=8),
        ),
    ]
