# Generated by Django 3.1.7 on 2021-04-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210415_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='serviced_item',
            field=models.BooleanField(default=False),
        ),
    ]
