# Generated by Django 3.1.7 on 2021-05-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_serviced_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['business', 'name']},
        ),
    ]
