# Generated by Django 3.2.3 on 2021-06-23 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_alter_businesspermissions_allowed'),
        ('chat', '0002_room_unique room per user'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.employee'),
        ),
    ]
